// AUTO-GENERATED by scripts/deploy.ts, do not edit by hand.
// Network: botchain (chainId 677)
// Deployed: 2026-08-31T11:47:06.075Z
export const CONTRACT_ADDRESSES = {
  BudgetVault: "0x3822E863D851DfC9CD0cfaF687195928461f72e4",
  AgentRegistry: "0x521C15E3cF59a062204279EC715e81859d95B5AF",
  CircuitBreaker: "0x959A3B3d2856288E044136dAF3e7823f8dD7A449",
} as const;

export const DEPLOYED_CHAIN_ID = 677;
