import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  const balance = await ethers.provider.getBalance(deployer.address);

  console.log("─".repeat(60));
  console.log("Sent, On-Chain Agent Circuit Breaker");
  console.log("Network :", network.name, `(chainId ${network.config.chainId})`);
  console.log("Deployer:", deployer.address);
  console.log("Balance :", ethers.formatEther(balance), "BOT");
  console.log("─".repeat(60));

  // 1. BudgetVault, holds escrowed BOT.
  const vault = await (await ethers.getContractFactory("BudgetVault")).deploy();
  await vault.waitForDeployment();
  const vaultAddress = await vault.getAddress();
  console.log("BudgetVault    :", vaultAddress);

  // 2. AgentRegistry, knows the vault so it can escrow at registration.
  const registry = await (await ethers.getContractFactory("AgentRegistry")).deploy(vaultAddress);
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log("AgentRegistry  :", registryAddress);

  // 3. CircuitBreaker, the kill switch.
  const breaker = await (
    await ethers.getContractFactory("CircuitBreaker")
  ).deploy(registryAddress, vaultAddress);
  await breaker.waitForDeployment();
  const breakerAddress = await breaker.getAddress();
  console.log("CircuitBreaker :", breakerAddress);

  // 4. Wire permissions. The registry locks escrow; the breaker releases it and
  //    is the only writer of usage counters.
  console.log("\nWiring permissions…");
  await (await vault.setBreaker(breakerAddress, true)).wait();
  console.log("  vault    -> breaker authorized");
  await (await vault.setBreaker(registryAddress, true)).wait();
  console.log("  vault    -> registry authorized (escrow lock)");
  await (await registry.setAuthorized(breakerAddress, true)).wait();
  console.log("  registry -> breaker authorized (usage writes)");

  // 5. Persist addresses + ABIs for the frontend and the Python runner.
  const deployment = {
    network: network.name,
    chainId: Number(network.config.chainId),
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    contracts: {
      BudgetVault: vaultAddress,
      AgentRegistry: registryAddress,
      CircuitBreaker: breakerAddress,
    },
  };

  const deployDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(deployDir, { recursive: true });
  fs.writeFileSync(
    path.join(deployDir, `${network.name}.json`),
    JSON.stringify(deployment, null, 2)
  );

  writeFrontendConfig(deployment);
  exportAbis();

  console.log("\n✅ Deployment complete.");
  console.log(JSON.stringify(deployment.contracts, null, 2));
  console.log("\nAddresses written to deployments/ and frontend/src/config/addresses.ts");
}

/** Keep the frontend's address book in sync with the latest deployment. */
function writeFrontendConfig(deployment: any) {
  const dir = path.join(__dirname, "..", "frontend", "src", "config");
  if (!fs.existsSync(dir)) return;

  const body = `// AUTO-GENERATED by scripts/deploy.ts, do not edit by hand.
// Network: ${deployment.network} (chainId ${deployment.chainId})
// Deployed: ${deployment.deployedAt}
export const CONTRACT_ADDRESSES = {
  BudgetVault: "${deployment.contracts.BudgetVault}",
  AgentRegistry: "${deployment.contracts.AgentRegistry}",
  CircuitBreaker: "${deployment.contracts.CircuitBreaker}",
} as const;

export const DEPLOYED_CHAIN_ID = ${deployment.chainId};
`;
  fs.writeFileSync(path.join(dir, "addresses.ts"), body);
}

/** Export minimal ABIs consumed by the frontend and agent-runner. */
function exportAbis() {
  const names = ["BudgetVault", "AgentRegistry", "CircuitBreaker"];
  const targets = [
    path.join(__dirname, "..", "frontend", "src", "config", "abis"),
    path.join(__dirname, "..", "agent-runner", "abis"),
  ];

  for (const target of targets) {
    fs.mkdirSync(target, { recursive: true });
    for (const name of names) {
      const artifact = JSON.parse(
        fs.readFileSync(
          path.join(__dirname, "..", "artifacts", "contracts", `${name}.sol`, `${name}.json`),
          "utf8"
        )
      );
      fs.writeFileSync(
        path.join(target, `${name}.json`),
        JSON.stringify(artifact.abi, null, 2)
      );
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
